#pragma once

#define SHADER_PROGRAM_COUNT 5

#define SHADER_PROGRAM_DEFAULT 0
#define SHADER_PROGRAM_GAME_OF_LIFE 1
#define SHADER_PROGRAM_TEXELMODIFY 2
#define SHADER_PROGRAM_INITTEXTURECOLOUR 3
#define SHADER_PROGRAM_MOUSETOSCREEN 4

#define TOTAL_CELLGRID_TEXTURE 2

#define CELLGRID_TEXTURE_PROCESS 0
#define CELLGRID_TEXTURE_DISPLAY 1

#define GRID_MAX_WIDTH_DEFAULT 5000 //13040
#define GRID_MAX_HEIGHT_DEFAULT 5000 //13040

#define DEFAULT_VALUE_CHANGE 10.0f